// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.1
// source: transacao.proto

package transacao

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TransacaoService_ProcessTransacao_FullMethodName = "/transacao.TransacaoService/ProcessTransacao"
)

// TransacaoServiceClient is the client API for TransacaoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransacaoServiceClient interface {
	ProcessTransacao(ctx context.Context, in *TransacaoRequest, opts ...grpc.CallOption) (*TransacaoResponse, error)
}

type transacaoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransacaoServiceClient(cc grpc.ClientConnInterface) TransacaoServiceClient {
	return &transacaoServiceClient{cc}
}

func (c *transacaoServiceClient) ProcessTransacao(ctx context.Context, in *TransacaoRequest, opts ...grpc.CallOption) (*TransacaoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransacaoResponse)
	err := c.cc.Invoke(ctx, TransacaoService_ProcessTransacao_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransacaoServiceServer is the server API for TransacaoService service.
// All implementations must embed UnimplementedTransacaoServiceServer
// for forward compatibility.
type TransacaoServiceServer interface {
	ProcessTransacao(context.Context, *TransacaoRequest) (*TransacaoResponse, error)
	mustEmbedUnimplementedTransacaoServiceServer()
}

// UnimplementedTransacaoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransacaoServiceServer struct{}

func (UnimplementedTransacaoServiceServer) ProcessTransacao(context.Context, *TransacaoRequest) (*TransacaoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessTransacao not implemented")
}
func (UnimplementedTransacaoServiceServer) mustEmbedUnimplementedTransacaoServiceServer() {}
func (UnimplementedTransacaoServiceServer) testEmbeddedByValue()                          {}

// UnsafeTransacaoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransacaoServiceServer will
// result in compilation errors.
type UnsafeTransacaoServiceServer interface {
	mustEmbedUnimplementedTransacaoServiceServer()
}

func RegisterTransacaoServiceServer(s grpc.ServiceRegistrar, srv TransacaoServiceServer) {
	// If the following call pancis, it indicates UnimplementedTransacaoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransacaoService_ServiceDesc, srv)
}

func _TransacaoService_ProcessTransacao_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransacaoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransacaoServiceServer).ProcessTransacao(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransacaoService_ProcessTransacao_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransacaoServiceServer).ProcessTransacao(ctx, req.(*TransacaoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TransacaoService_ServiceDesc is the grpc.ServiceDesc for TransacaoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransacaoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transacao.TransacaoService",
	HandlerType: (*TransacaoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessTransacao",
			Handler:    _TransacaoService_ProcessTransacao_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transacao.proto",
}
